### ISSUE TITLE
SERVER=random

### ISSUE THREAD

**Issue by ffischer1984** [polkaned/dockerfiles#11]
Hi,
it would be an nice enhancement if it could be connect to a random location / to increase the chance to get a new ip-adress after each restart

**Comment by polkaned** [comment]
Hi,
I do not maintain the binary and their options.
You should ask expresspvn to add this kind of parameter.

**Comment by ffischer1984** [comment]
Ah yeah thanks that's correct. Is there a reason why you don't use https://github.com/philipperemy/expressvpn-python
