### ISSUE TITLE
How to use with MACVLAN ?

### ISSUE THREAD

**Issue by stefanopog** [polkaned/dockerfiles#16]
Hello
i wish to create a container based on this image in a way that the container would be available within my Local Network. 
Ultimately, the goal is to have my AppleTV to use the container as a proxy to connect to expressVPN

Could you pls help me figure out how to create a docker compose file that would allow me to reach my goal ?
thanks so much
best regards
/Stefano

**Comment by plozachm** [comment]
So you want your Apple TV to connect through proxy, which itself is connected to a VPN. I think you will need another container for the proxy which will have a/several port(s) on your LAN, this container will connect to the vpn container network like that:
```
    network_mode: "service:vpn"
    depends_on:
      - vpn
```
Is this what you needed?
