### ISSUE TITLE
"Please activate your account"

### ISSUE THREAD

**Issue by schmurnan** [polkaned/dockerfiles#19]
Hi there,

Just updated my Docker container and now can't reconnect, keep getting the following in the logs:

```
Restarting expressvpnd daemon... [ OK ]
spawn expressvpn activate
Enter activation code: 
Activating...
n
Please activate your account.
```

Activation code is fine, hasn't changed and is used elsewhere.

Any suggestions, please?

**Comment by schmurnan** [comment]
Added a screenshot.
<img width="316" alt="Screenshot 2020-09-21 at 19 14 46" src="https://user-images.githubusercontent.com/62752073/93806352-ef3bc680-fc40-11ea-8e27-b754a85d5624.png">

**Comment by silentArtifact** [comment]
I'm also seeing this same issue. Is there any general advice on what's going on there?

**Comment by munib-dihlab** [comment]
Facing same issue with running the container from docker run command, although it works fine following the docker-compose example.

I was able to get inside the container and check all the env vars, they look fine. Inside the container, I was able to run `/bin/sh entrypoint.sh` and it worked fine too. What could be causing this issue at startup?
