### ISSUE TITLE
Does the container need to keep running?

### ISSUE THREAD

**Issue by ThomasDalla** [polkaned/dockerfiles#2]
Using the container on a Synology NAS just exits the container after the connection is made:

![image](https://user-images.githubusercontent.com/609945/69007147-d7fdbf80-0931-11ea-9539-b663cb58ba1e.png)

Any way to keep it running or does it not need to keep running?

**Comment by polkaned** [comment]
Add `/bin/bash` and the end of the `docker run` command.

**Comment by ThomasDalla** [comment]
Simple, thanks.
