### ISSUE TITLE
Doesn't block traffic on start up

### ISSUE THREAD

**Issue by jaroslawjanas** [polkaned/dockerfiles#22]
Expressvpn
The traffic isn't blocked during the container start up or while establishing the connection.
This is problematic if another container accesses the network in that short time-span.

**Comment by plozachm** [comment]
You're right, one solution could be:
```
➜  dockerfiles git:(master) ls -l
total 4
-rwxrwxr-x 1 p p 360 Nov  2  2019 build_and_push.sh
drwxrwxr-x 1 p p 134 Oct 11 13:28 expressvpn
➜  dockerfiles git:(master) ls -l expressvpn
total 20
-rw-rw-r-- 1 p p  749 Oct 11 13:24 Dockerfile
-rw-rw-r-- 1 p p  276 Oct 11 12:33 entrypoint.sh
-rw-rw-r-- 1 p p  467 Oct 11 12:30 expressvpnActivate.sh
-rwxr-xr-x 1 p p  205 Oct 11 13:07 healthcheck.sh
-rw-rw-r-- 1 p p 1803 Jul 31 10:17 README.md
➜  dockerfiles git:(master) grep health expressvpn/*
expressvpn/Dockerfile:COPY healthcheck.sh /tmp/healthcheck.sh
expressvpn/Dockerfile:HEALTHCHECK CMD /tmp/healthcheck.sh >/dev/null
➜  dockerfiles git:(master) cat expressvpn/healthcheck.sh
#!/usr/bin/expect
spawn expressvpn status
expect {
    "Connected to UK - London" {
        exit 0
    }
    "Not connected" {
        exit 1
    }
    "Not activated" {
        exit 1
    }
}
expect eof
```
The healthcheck fails according to the container geolocation (should be a parameter but to showcase it was good enough) so no dependent container will use it until properly connected to _UK - London_ (container status is _starting_ until it changes to _healthy_). After that if the connection is lost, expressvpn locks its network. 
Now, in the docker-compose.yml I configure it like this for the containers which depend on the vpn:
```
    restart: unless-stopped
    network_mode: "service:vpn"
    depends_on:
      vpn:
        condition: service_healthy
```

I still think it still should be tested/improved but maybe it helps your case.

**Comment by plozachm** [comment]
Hi,
I have part of the solution I think, we could add a healthcheck to the container by modifying 2 files
```
➜  dockerfiles git:(master) grep -i heal expressvpn/Dockerfile
COPY healthcheck.sh /tmp/healthcheck.sh
HEALTHCHECK --interval=20s --timeout=3 --start-period=8 --retries=1  CMD /tmp/healthcheck.sh
➜  dockerfiles git:(master) cat expressvpn/healthcheck.sh
#!/bin/bash
servername=`expressvpn list | grep "${SERVER}"| cut -f2- | sed -e 's/^[\s\t]*//' | tr -d '\n'`
connected=`expressvpn status | grep "${servername}" | wc -l`
[[ $connected -eq 1 ]] && exit 0 || exit 1
➜  dockerfiles git:(master)
```
Then in the docker-compose file, when we link another container to this container's network:
```
    network_mode: "service:vpn"
    depends_on:
      vpn:
        condition: service_healthy
```
Now, linked containers of the docker-compose.yml should not start before the vpn container is up and connected to the proper VPN.
Nevertheless, if you enter the vpn container and disconnect the expressvpn manually without stopping the container, the unhealtiness would be detected in 20 seconds or so but the network will still be reachable.

**Comment by jaroslawjanas** [comment]
@alno74d It's a nice workaround.
