### ISSUE TITLE
ERROR: The Compose file './docker-compose.yml' is invalid 

### ISSUE THREAD

**Issue by yuis-ice** [polkaned/dockerfiles#26]
Hi, I tried the docker compose example but I got an error as follows. 

$ docker-compose up
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for downloader: 'network_mode'
expressvpn.ports contains an invalid type, it should be an array

Thank you.

**Comment by yuis-ice** [comment]
Also, I tried following after some google and got an error also. 

```docker-compose.yml
version: '3.3'

services:
  expressvpn:
    container_name: expressvpn
    image: polkaned/expressvpn
    environment:
      - ACTIVATION_CODE={% your-activation-code %}
      - SERVER={% LOCATION/ALIAS/COUNTRY %}
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    stdin_open: true
    tty: true
    command: /bin/bash
    privileged: true
    restart: unless-stopped
    ports:
      - "8000:8000"
      - "80:80"
      # ports of other containers that use the vpn (to access them locally)

  downloader:
    image: example/downloader
    container_name: downloader
    network_mode: service:expressvpn
    depends_on:
      - expressvpn
``` 

$ docker-compose up
Creating network "expressvpn_tmp_default" with the default driver
ERROR: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network

Thanks.

**Comment by tanis80** [comment]
Works for me with below config:
services: 
    vpn:
      container_name: express-vpn
      image: polkaned/expressvpn
      environment:
        - ACTIVATION_CODE=${EXPRESSVPN_CODE}
      cap_add:
        - NET_ADMIN
      devices: 
        - /dev/net/tun
      stdin_open: true
      tty: true
      command: /bin/bash
      privileged: true
      restart: unless-stopped
      ports:
        - 9091:9091/tcp # transmission portal

   transmission:
        container_name: transmission
        environment: 
          - PUID=1000
          - PGID=1000
          - TZ=Europe/London
          - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
          - USER=${TRANSMISSION_USERNAME}
          - PASS=${TRANSMISSION_PASSWORD}
        volumes:
          - /volume1/docker/transmission:/config 
          - /volume1/Downloads/torrent:/downloads
          - /volume1/Downloads/torrent/watch:/watch
        restart: unless-stopped
        image: linuxserver/transmission
        network_mode: service:vpn
        depends_on:
          - vpn
      

Stange, the configuration look correct. Is it possible some other issue related your docker configuration? 

You can try to remove your unused network: 
docker network prune
