### ISSUE TITLE
Network Lock functionality not working

### ISSUE THREAD

**Issue by 11matt556** [polkaned/dockerfiles#29]
It seems that the network block functionality is not blocking internet access when the VPN drops.

The below commands were run from within the expressvpn container.

root@58f7559ff99e:/# curl ifconfig.me
(My real ip)

root@58f7559ff99e:/# expressvpn status
Unable to connect.

   - Check your internet connection or try a different location.
   - Internet traffic is blocked to protect your privacy.
   - To retry the connection, type 'expressvpn connect'
   - To disconnect from the VPN and unblock internet traffic, type 'expressvpn disconnect'

root@58f7559ff99e:/# expressvpn connect
Connecting to Canada - Toronto...       100.0%
Connected to Canada - Toronto

   - To check your connection status, type 'expressvpn status'.
   - If your VPN connection unexpectedly drops, internet traffic will be blocked to protect your privacy.
   - To disable Network Lock, disconnect ExpressVPN then type 'expressvpn preferences set network_lock off'.
   
root@58f7559ff99e:/# curl ifconfig.me
(VPN IP)

I was also able to curl example.com and other websites. If the network lock was working I would expect to be unable to reach those sites,

**Comment by rupaa105** [comment]
@11matt556 Were you ever able to get connected to the Toronto servers?  I can't get connected to any servers on my synology docker.

**Comment by 11matt556** [comment]
@rupaa105 I never had any issues making the initial connection. It was more that it would drop after a few days and fail to reconnect. The concern for me was that it did not automatically block traffic when the VPN connection dropped. I have since switched away from ExpressVPN, but I never got the automatic traffic blocking to work as intended.

**Comment by bbwebb** [comment]
I have the same issue.  If the VPN disconnects my network connection while inside the docker container is unavailable (e.g. curl ipinfo.io returns Unable to connect), but any of my docker containers that are using the expressvpn container for network access are able to use my actual network (ISP provided IP).  I'm assuming it has something to do with my expressvpn container since if I stop the expressvpn container, any other containers using the expressvpn container lose access to the network.

**Comment by BrooklynMan** [comment]
this is a major issue. is there any resolution?

**Comment by LeehamElectronics** [comment]
Still looking for a resolution...

**Comment by HeadbangGang** [comment]
Still interested in a resolution as well.
