### ISSUE TITLE
Expressvpn not providing a vpn connect, but still allowing internet access

### ISSUE THREAD

**Issue by MatthewJC3** [polkaned/dockerfiles#38]
curl ifconfig.io revealed that the docker container getting its internet access through expressvpn and expressvpn itself were both going through my normal IP. Afterr restarting the container it was fixed, however I dont understand why it was still providing internet access.

**Comment by robwolff3** [comment]
Im also wondering if there is a way for the container to fail to no traffic. I discovered normal internet traffic with an activation failure in the logs. Restart fixed it but my ip was exposed.
