### ISSUE TITLE
Feature Request: Add curl to image

### ISSUE THREAD

**Issue by leloberg** [polkaned/dockerfiles#4]
I find myself keep adding curl to this container so that I can run 

`curl ifconfig.co/json`

to verify that the VPN connection is actually active.

I keep deleting and recreating my containers all the time, so would it be possible to add curl as default to this image, to make my life easier? :)

**Comment by polkaned** [comment]
Why you don't use `expressvpn status`?

**Comment by leloberg** [comment]
I do that too, I just get more and better information from the ifconfig.co site. And I like to be able to run commands do check for dnsleaks too. This is no big deal though, so if this makes the docker image a lot bigger or more compromised I'm all fine with this being closed and declined :)

**Comment by polkaned** [comment]
Don't worry: the size is the same.
It is added.
