### ISSUE TITLE
Feature Request: Healthcheck

### ISSUE THREAD

**Issue by RichBrew** [polkaned/dockerfiles#44]
ExpressVPN tends to disconnect randomly, and does not re-connect automatically (This happens on my Windows client as well, so it seems to be an ExpressVPN issue)

I attempted including the following when creating the container, but it seems ping isn't installed on the image.

    healthcheck:
      test: "ping -c 1 www.google.com || exit 1"
      interval: 5s
      timeout: 10s
      retries: 3

Please include ping in the image, or some other viable mechanism that can be used to check if the connection is live using a healthcheck command. This would use of monitoring to automatically restart the container if it is unhealthy.

I could just install it, but then it would need to be re-installed any time the image is updated.

**Comment by polkaned** [comment]
ping is added
