### ISSUE TITLE
Startup VPN activation sequence failing

### ISSUE THREAD

**Issue by VineST** [polkaned/dockerfiles#49]
When initializing my containers with docker compose, this error appears in ExpressVPN:
![image](https://github.com/polkaned/dockerfiles/assets/6686964/a04ca6f2-f5e2-4b8f-bf77-10d5d4a34db9)
I tried `expressvpn activate` and I was told that the account is already activated. However, I was then able to run `expressvpn connect` and successfully connect immediately. Why is it failing to automatically activate at startup, though?

The activation key is in place as expected:
![image](https://github.com/polkaned/dockerfiles/assets/6686964/21eb491d-be33-478c-a79c-2811d136cf41)

I notice that the readme says to run this as a base layer. I'm quite new to docker so I'm not sure what this means exactly; it looks like from a glance online that this is configured in the dockerfile, which I don't typically have to modify as an end user?
Because it's a dependency for all my other containers (as instructed in the readme), I can evidently see the docker-compose script properly initializing it first and then reform the others, but perhaps this alone is not enough.
When I stop and restart the containers after this first manual connection, things appear to proceed fine. Looks like the issue only occurs upon first recreating the instance.

**Comment by aquarist684** [comment]
> When initializing my containers with docker compose, this error appears in ExpressVPN: ![image](https://user-images.githubusercontent.com/6686964/242757621-a04ca6f2-f5e2-4b8f-bf77-10d5d4a34db9.png) I tried `expressvpn activate` and I was told that the account is already activated. However, I was then able to run `expressvpn connect` and successfully connect immediately. Why is it failing to automatically activate at startup, though?
> 
> The activation key is in place as expected: ![image](https://user-images.githubusercontent.com/6686964/242757587-21eb491d-be33-478c-a79c-2811d136cf41.png)
> 
> I notice that the readme says to run this as a base layer. I'm quite new to docker so I'm not sure what this means exactly; it looks like from a glance online that this is configured in the dockerfile, which I don't typically have to modify as an end user? Because it's a dependency for all my other containers (as instructed in the readme), I can evidently see the docker-compose script properly initializing it first and then reform the others, but perhaps this alone is not enough. When I stop and restart the containers after this first manual connection, things appear to proceed fine. Looks like the issue only occurs upon first recreating the instance.

Did you ever solve this ? I am getting the exact same issue.

**Comment by VineST** [comment]
@aquarist684 Sadly no, although it seems to have become less common. Looks like the VPN will typically fail a few times and ultimately connect now. I haven't changed any config for the VPN instance itself.

**Comment by aquarist684** [comment]
@VineST .. switched to https://hub.docker.com/r/misioslav/expressvpn .. worked on first compose.
