### ISSUE TITLE
Unable to connect to ..

### ISSUE THREAD

**Issue by gerberanub** [polkaned/dockerfiles#56]
root@ece504aaefcf:/# expressvpn connect
Connecting to Smart Location...
Connecting to Japan - Shibuya...
Unable to connect to Japan - Shibuya

   - Check your internet connection or try a different location.
   - Internet traffic is blocked to protect your privacy.
   - To retry the connection, type 'expressvpn connect'
   - To disconnect from the VPN and unblock internet traffic, type 'expressvpn disconnect'
root@ece504aaefcf:/# expressvpn diagnostics
Client Version: 0.0.1default
Client Shared Version: v23.21.0
OS Name: linux
OS Version: Debian GNU/Linux 11
Internal diagnostics data:
D01: 212, OK
D02: 212, OK
D03: 210, OK
D04: 757, OK
D05: 757, OK
D06: 188, OK
D07: 214, OK
D08: 214, OK
D09: 188, OK
D10: 757, OK
D11: 757, OK
D12: N, N
D13: www.2spb2qq8pnqmv.net/api
D14: Japan - Shibuya
D15: auto
D17: 757, OK
D18: 0
Network Lock:         enabled, allow access to local devices
DNS leak protection:  enabled
IPv6 leak protection: enabled
Selected location:    Japan - Shibuya (Smart Location)

==============================================

Connecting to Japan - Shibuya, ip: 24.123.193.169, protocol: lightway_udp

Client Version: 0.0.1default
Client Shared Version: v23.21.0
OS Name: linux
OS Version: Debian GNU/Linux 11
Internal diagnostics data:
D01: 196, OK
D02: 196, OK
D03: 194, OK
D04: 741, OK
D05: 741, OK
D06: 172, OK
D07: 198, OK
D08: 198, OK
D09: 172, OK
D10: 741, OK
D11: 741, OK
D12: N, N
D13: www.2spb2qq8pnqmv.net/api
D14: Japan - Shibuya
D15: auto
D17: 741, OK
D18: 0

**Comment by gerberanub** [comment]
my docker compose is


---
version: "2.1"
services:
  expressvpn:
    container_name: expressvpn
    image: polkaned/expressvpn
    environment:
      - ACTIVATION_CODE=XXXXXXXXXXX
      #- SERVER=smart
      #- PREFERRED_PROTOCOL=lightway_udp
      #- LIGHTWAY_CIPHER=chacha20
    cap_add:
      - NET_ADMIN
    devices: 
      - /dev/net/tun
    stdin_open: true
    tty: true
    command: /bin/bash
    privileged: true
    restart: unless-stopped
    ports:
      # ports of other containers that use the vpn (to access them locally)
      - 8081:80
      - 5002:5000
      - 51413:51413
      - 6880:6881/udp
  rutorrent:
    image: ghcr.io/linuxserver/rutorrent
    container_name: rutorrent
    environment:
      - PUID=1026
      - PGID=100
    volumes:
      - /volume2/docker/rutorrent+expressvpn/rutorrent/config:/config
      - /volume1/torrent0/rutorrent:/downloads
      - /volume2/sg16tb0/TV-다큐/인사이트 아시아 - 누들로드 Noodle Road (2008):/uploads
    restart: unless-stopped
    network_mode: service:expressvpn
    depends_on:
      - expressvpn

**Comment by thaggren** [comment]
Same issue for me. Tried all protocols, no eval.
Not sure what changed.

**Comment by polkaned** [comment]
See this https://github.com/polkaned/dockerfiles/issues/55
