### ISSUE TITLE
ExpressVPN :latest unable to connect

### ISSUE THREAD

**Issue by Anqui3tas** [polkaned/dockerfiles#57]
decided to try to pull the latest image to see if it would connect, I've gone back to 3.57.0.3-1.653ac494 as it has no issues. 

unable to connect to any servers. 

yaml config:

    expressvpn:
        image: polkaned/expressvpn:latest
        container_name: expressvpn
        environment:
            - ACTIVATION_CODE= [my code removed to post]
        cap_add:
            - NET_ADMIN
        devices:
            - "/dev/net/tun:/dev/net/tun"
        privileged: true
        tty: true
        ports: [removed to shorten post]
        command: /bin/bash
        restart: unless-stopped

**Comment by didster** [comment]
Same.  Possibly linked to #55
