### ISSUE TITLE
Feature Request: Add network lock option

### ISSUE THREAD

**Issue by Appyx** [polkaned/dockerfiles#7]
Hi, thanks for creating the container 👍 

It would be nice to be able to enable the network lock.
I tried it manually inside the container but the error `network lock not available`shows.
I have no idea how to enable it, maybe you have an idea.

**Comment by polkaned** [comment]
Hi,
No worry, it is enabled by default:
```
root@d9732d856bb6:/# expressvpn status

Connected to XXX

   - If your VPN connection unexpectedly drops, internet traffic will be blocked to protect your privacy.
   - To disable Network Lock, disconnect ExpressVPN then type 'expressvpn preferences set network_lock off'.
```

**Comment by Appyx** [comment]
Yeah seems like it.
But when manually disconnecting, the internet connection is not getting blocked, at least in my case.
Can you observe this behaviour too?

**Comment by polkaned** [comment]
This behavior is by design:

> Network Lock becomes active as soon as you attempt to connect to a VPN server location, and it will remain active until you choose to disconnect.

https://www.expressvpn.com/support/troubleshooting/network-lock/

**Comment by Appyx** [comment]
Oh right, didn't know that :D
